/**
 * @file
 * AUTOGENERATED runner of the test suite.
 *
 * Returns non-zero in case at least 1 testcase failed.
 *
 * @copyright Copyright © 2022-2024, Matjaž Guštin <dev@matjaz.it>
 * <https://matjaz.it>. All rights reserved.
 * @license BSD 3-Clause License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS “AS IS”
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "atto.h"
#include "xtr.h"
#include "xtrtest.h"

int
main(void)
{
    printf("Testing libxtr M:%d m:%d bf:%d = v%s\\n",
           XTR_API_VERSION_MAJOR,
           XTR_API_VERSION_MINOR,
           XTR_API_VERSION_BUGFIX,
           XTR_API_VERSION);
    // clang-format off
    // @formatter: off
    // BEGIN OF AUTOMATED LISTING OF ALL XTRTEST TESTCASES
    xtrtest_clone_valid_1_char_xtr();
    xtrtest_clone_valid_empty_xtr();
    xtrtest_clone_validaaaa_6_char_xtr();
    xtrtest_clone_with_capacity_valid_1_char_xtr_less_capacity();
    xtrtest_clone_with_capacity_valid_1_char_xtr_more_capacity();
    xtrtest_clone_with_capacity_valid_1_char_xtr_same_capacity();
    xtrtest_clone_with_capacity_valid_empty_xtr_more_capacity();
    xtrtest_clone_with_capacity_valid_empty_xtr_same_capacity();
    xtrtest_free_valid();
    xtrtest_free_valid_on_null_input();
    xtrtest_from_str_fail_malloc();
    xtrtest_from_str_repeated_fail_malloc();
    xtrtest_from_str_repeated_valid_1_byte_string_0_times();
    xtrtest_from_str_repeated_valid_1_byte_string_1_times();
    xtrtest_from_str_repeated_valid_1_byte_string_2_times();
    xtrtest_from_str_repeated_valid_6_bytes_string_3_times();
    xtrtest_from_str_repeated_valid_empty_string();
    xtrtest_from_str_repeated_valid_empty_string_0_times();
    xtrtest_from_str_repeated_valid_null_0_times();
    xtrtest_from_str_repeated_valid_null_1_time();
    xtrtest_from_str_repeated_with_capacity_fail_malloc();
    xtrtest_from_str_repeated_with_capacity_valid_1_byte_string_0_times_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_1_byte_string_0_times_7_space();
    xtrtest_from_str_repeated_with_capacity_valid_1_byte_string_1_times_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_1_byte_string_1_times_7_space();
    xtrtest_from_str_repeated_with_capacity_valid_1_byte_string_2_times_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_1_byte_string_2_times_7_space();
    xtrtest_from_str_repeated_with_capacity_valid_6_bytes_string_3_times_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_6_bytes_string_3_times_20_space();
    xtrtest_from_str_repeated_with_capacity_valid_empty_string_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_empty_string_0_times_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_empty_string_0_times_7_space();
    xtrtest_from_str_repeated_with_capacity_valid_empty_string_7_space();
    xtrtest_from_str_repeated_with_capacity_valid_null_0_times_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_null_0_times_7_space();
    xtrtest_from_str_repeated_with_capacity_valid_null_1_time_0_space();
    xtrtest_from_str_repeated_with_capacity_valid_null_1_time_7_space();
    xtrtest_from_str_valid_1_byte_string();
    xtrtest_from_str_valid_6_bytes_string();
    xtrtest_from_str_valid_empty_string();
    xtrtest_from_str_valid_null();
    xtrtest_from_str_with_capacity_fail_malloc();
    xtrtest_from_str_with_capacity_valid_1_char_0_bytes();
    xtrtest_from_str_with_capacity_valid_1_char_1_bytes();
    xtrtest_from_str_with_capacity_valid_1_char_2_bytes();
    xtrtest_from_str_with_capacity_valid_6_chars_10_bytes();
    xtrtest_from_str_with_capacity_valid_6_chars_4_bytes();
    xtrtest_from_str_with_capacity_valid_6_chars_6_bytes();
    xtrtest_from_str_with_capacity_valid_empty_string_0_bytes();
    xtrtest_from_str_with_capacity_valid_empty_string_15_bytes();
    xtrtest_from_str_with_capacity_valid_empty_string_1_byte();
    xtrtest_from_str_with_capacity_valid_null_string_0_bytes();
    xtrtest_from_str_with_capacity_valid_null_string_6_bytes();
    xtrtest_getters_do_nothing_on_null_input();
    xtrtest_is_empty_valid_empty();
    xtrtest_is_empty_valid_empty_with_capacity();
    xtrtest_is_empty_valid_non_empty();
    xtrtest_is_empty_valid_null();
    xtrtest_is_spaces_valid_different_whitespaces();
    xtrtest_is_spaces_valid_empty();
    xtrtest_is_spaces_valid_empty_with_capacity();
    xtrtest_is_spaces_valid_many_spaces();
    xtrtest_is_spaces_valid_non_spaces();
    xtrtest_is_spaces_valid_not_only_whitespaces();
    xtrtest_is_spaces_valid_null();
    xtrtest_is_spaces_valid_single_space();
    xtrtest_new_empty_fail_malloc();
    xtrtest_new_empty_valid();
    xtrtest_new_ensure_fail_size_overflow();
    xtrtest_new_with_capacity_fail_malloc();
    xtrtest_new_with_capacity_fail_size_overflow();
    xtrtest_new_with_capacity_valid_allocate_0_bytes();
    xtrtest_new_with_capacity_valid_allocate_15_bytes();
    xtrtest_new_with_capacity_valid_allocate_1_byte();
    xtrtest_new_with_capacity_valid_allocate_ffff_plus_1_bytes();
    xtrtest_zeros_fail_malloc();
    xtrtest_zeros_valid_1_byte();
    xtrtest_zeros_valid_6_bytes();
    xtrtest_zeros_valid_empty();
    // END OF AUTOMATED LISTING OF ALL XTRTEST TESTCASES
    // clang-format on
    // @formatter: on
    atto_report();
    return atto_at_least_one_fail;
}
